version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: su -m myuser -c "python manage.py collectstatic --noinput" && su -m myuser -c "python manage.py makemigrations service" && su -m myuser -c "python manage.py migrate" && su -m myuser -c "gunicorn serviceapp.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/app  # mount current directory inside container
      - ./static:/static
      - ./media:/media
    # set up links so that web knows about db and redis
    links:
      - db
      - redis
    depends_on:
      - db
    expose:
      - "8000"

  db:
    restart: always
    hostname: db
    image: postgres:latest

  redis:
    restart: always
    image: redis:latest
    hostname: redis
    ports:
     - '6379:6379'

  worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: su -m myuser -c "celery worker -A serviceapp.celeryconf -Q default -n default@%h"
    volumes:
      - .:/app
    links:
      - db
      - redis
