version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static/
      - ./media:/media/
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn serviceapp.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/src
      - ./static:/static/
      - ./media:/media/
    links:
      - redis
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01

  redis:
    image: redis:latest
    container_name: rd01
    ports:
     - '6379:6379'

  celery:
    build: .
    container_name: cl01
    command: celery worker --app=app.tasks
    volumes:
      - ..:/src
    links:
      - db
      - redis