version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng02
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media/
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: dg02
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn serviceapp.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    links:
      - redis
    volumes:
      - .:/src
      - ./static:/static/
      - ./media:/media/
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps02
    ports:
     - "5432"

  redis:
    image: redis:latest
    container_name: rd02
    ports:
     - '6379:6379'

  celery:
    build: .
    container_name: cl02
    command: celery worker --app=app.tasks
    volumes:
       - .:/src
    links:
      - db
      - redis
