# Generated by Django 2.0.5 on 2018-05-23 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=200)),
                ('house_id', models.IntegerField()),
                ('house_number', models.IntegerField()),
                ('flat_number', models.IntegerField()),
                ('flat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.CharField(max_length=400)),
                ('name_short', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('estimate', models.IntegerField()),
                ('type', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('status_id', models.IntegerField()),
                ('status_updated_time', models.DateTimeField()),
                ('speciality', models.CharField(max_length=200)),
                ('spent_time', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Address')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Engineer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_begin', models.DateTimeField()),
                ('to', models.DateTimeField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.TimeSlot'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='time_slots',
            field=models.ManyToManyField(to='service.TimeSlot'),
        ),
    ]
