# Generated by Django 2.0.5 on 2018-05-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='from_begin',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='to',
            new_name='to_date',
        ),
        migrations.AlterField(
            model_name='engineer',
            name='time_slots',
            field=models.ManyToManyField(to='service.timeslot'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.address'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.engineer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.timeslot'),
        ),
    ]
