# Generated by Django 2.0.5 on 2018-05-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180527_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='engineer',
            name='time_slots',
            field=models.ManyToManyField(to='service.timeslot'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.speciality'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.address'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.engineer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.timeslot'),
        ),
    ]
