# Generated by Django 2.0.5 on 2018-06-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20180531_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='services',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.AlterField(
            model_name='engineer',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Speciality'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Speciality'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Speciality'),
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
