# Generated by Django 2.0.6 on 2018-06-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20180604_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Speciality'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Speciality'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Speciality'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='spent_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
