# Generated by Django 2.0.6 on 2018-06-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20180605_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='time_slots',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='service',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='speciality',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
