# Generated by Django 2.0.6 on 2018-06-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20180605_0731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlotToEngineer',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='time_slots',
        ),
    ]
