# Generated by Django 2.0.6 on 2018-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20180605_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(default=1, upload_to='services'),
            preserve_default=False,
        ),
    ]
